catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    # We are going to define all of our app-level urls
    # We need to add an import statment to link our files

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='index'),
#Get /cats/1
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),

    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    
    path('cats/<int:cat_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('cats/<int:cat_id>/add_photo/', views.add_photo, name='add_photo'),

    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from random import choices
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
    )

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})


# Create your models here.
class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    # Add the Many:Many relationship
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #changes to instance methods do not require re-generation / running migrations
    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('detail', kwargs={'cat_id': self.id})

class Feeding(models.Model):
    date = models.DateField()
    meal = models.CharField(
        max_length=1,
        # add the 'choices' filed option
        choices=MEALS,
        # set the default value for meal to be 'B'
        default=MEALS[0][0]
    )
    #Create a cat_id FK
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for cat_id: {self.cat_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from .models import Cat, Toy, Photo
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from .forms import FeedingForm
import boto3
import uuid

# Enviroment Variables
S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'cat-collector-persistence-teemy'

# Create your views here.

def signup(request):
    # handle POST Requests (signing up)
    error_message = ''
    if request.method == 'POST':
        # collect form inputs
        form = UserCreationForm(request.POST) # <= fills out the form with the form values from the request
        # validate form inputs
        if form.is_valid():
            # save the new user to the database
            user = form.save()
            # log the user in
            login(request, user)
            # redirect the user to the cats index
            return redirect('index')
        else:
        # if the user form is invalid - show an error message
            error_message = 'invalid credentials - please try again'
    # handle GET Requests (navigating the user to the signup page)
    # present the user with a fresh singup form
    form = UserCreationForm()
    context = {'form': form, 'error':error_message}
    return render(request, 'registration/signup.html', context)



def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def cats_index(request):
    cats = Cat.objects.filter(user=request.user)
    return render(request, 'cats/index.html', {'cats': cats})

# update this view function
@login_required
def cats_detail(request, cat_id):
  cat = Cat.objects.get(id=cat_id)
  if cat.user_id != request.user.id:
      return redirect('index')
  # Allows us to get all Toy objects and compares value between two lists
  toys_cat_doesnt_have = Toy.objects.exclude(id__in = cat.toys.all().values_list('id'))
  # instantiate FeedingForm to be rendered in the template
  feeding_form = FeedingForm()
  return render(request, 'cats/detail.html', {
    # include the cat and feeding_form in the context
    'cat': cat, 
    'feeding_form': feeding_form,
    # Add the toys to be displayed
    'toys': toys_cat_doesnt_have
  })

@login_required
def add_feeding(request, cat_id):
    # create the ModelForm using the data in request.POST
    form = FeedingForm(request.POST)
    #validate the from
    if form.is_valid():
        #don't save the form to the db until it has the cat_id assigned
        new_feeding = form.save(commit=False)
        new_feeding.cat_id = cat_id
        new_feeding.save()
    return redirect('detail', cat_id=cat_id)

@login_required
def assoc_toy(request, cat_id, toy_id):
    # Note that you can pass a toy's id instead of the whole object
    Cat.objects.get(id=cat_id).toys.add(toy_id)
    return redirect('detail', cat_id=cat_id)


@login_required
def add_photo(request, cat_id):
    # Collect the file asset from the request
    photo_file = request.FILES.get('photo-file', None)
    # check if file is present
    if photo_file:
        #create a reference to the s3 service from boto3
        s3 = boto3.client('s3')
        #create a unique identifier for each photo asset
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # cute_cat.png => as214k.png
        try:
            #attempt to upload image to aws
            s3.upload_fileobj(photo_file, BUCKET, key)
            # dynamically generate photo url
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # create an in-memory reference to a photo model instance
            photo = Photo(url=url, cat_id=cat_id)
            # save the instance to the database
            photo.save()

        except Exception as error:
            print('**********************')
            print('An error has occured with s3')
            print(error)
            print('**********************')
    
    return redirect('detail', cat_id=cat_id)






class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = ('name', 'breed', 'description', 'age')
    # success_url = '/cats/' 
    
    # This inherited method is called when a
     # valid cat form is being submitted
    def form_valid(self, form):
     # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the cat
     # Let the CreateView do its job as usual
        return super().form_valid(form)

class CatUpdate( LoginRequiredMixin, UpdateView):
    model = Cat
    fields = ('breed', 'description', 'age')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = '/cats/'

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = ('name', 'color')

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = ('name', 'color')

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys/'

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy
    template_name = 'toys/detail.html'

class ToyList(LoginRequiredMixin, ListView):
    model = Toy
    template_name = 'toys/index.html'

main_app/templates/cats/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Cat Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description }}</p>
        {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
        {% else %}
        <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cats_update' cat.id %}">Edit</a>
        <a href="{% url 'cats_delete' cat.id %}">Delete</a>
      </div>
    </div>
    {% for photo in cat.photo_set.all %}
      <img src="{{ photo.url }}" alt="{{ cat.name }}" class="responsive-img card-panel">
      {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' cat.id %}" method="post" enctype="multipart/form-data" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file" >
    <br>
    <br>
    <input type="submit" value="Upload Photo" class="btn green">
    </form>

  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' cat.id %}" method="post">
      {% csrf_token %} {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />
<div class="row">
    <div class="col s6">
        <h3>{{ cat.name }}'s Toys</h3>
        {% if cat.toys.count %} {% for toy in cat.toys.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span class="{{ toy.color.lower }}-text">{{ toy.color }}</span> {{ toy.name }}
                </span>
            </div>
        </div>
        {% endfor %} {% else %}
        <h5>No Toys :(</h5>
        {% endif %}
    </div>


    <!-- Available toys will come after this line -->
    <div class="col s6">
      <h3>Available Toys</h3>
      {% if toys.count %}
        {% for toy in toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span class="{{ toy.color.lower }}-text">{{ toy.color }}</span> {{ toy.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_toy' cat.id toy.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{cat.name}} Already Has All Toys Available</h5>
      {% endif %}
    </div>
</div>





<script>
  var dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  // add additional JS to initialize select below
  var selectEl = document.getElementById("id_meal");
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% block content %}

<h1>Cat List</h1>

{% for cat in cats %}
<div class="card">
  <a href="{% url 'detail' cat.id %}">
    <div class="card-content">
      <span class="card-title">{{ cat.name }}</span>
      <p>Breed: {{ cat.breed }}</p>
      <p>Description: {{ cat.description }}</p>
      {% if cat.age > 0 %}
      <p>Age: {{ cat.age }}</p>
      {% else %}
      <p>Age: Kitten</p>
      {% endif %}
    </div>
  </a>
</div>
{% endfor %} {% endblock %}